name: zoom_clone
description: A Zoom Clone Application Developed Using Flutter & Firebase.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  firebase_core: ^1.17.1
  cloud_firestore: ^3.1.17
  firebase_auth: ^3.3.19
  google_sign_in: ^5.3.2
  jitsi_meet: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/images/
